In [1]:
import numpy as np

In [2]:
# Difference Between List and Numpy (Time and Space)

In [3]:
li_arr = [i for i in range(100)]
np_arr = np.arange(100)
print(li_arr)
print(np_arr)




[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [7]:
#Size of one element in numpy array
print(np_arr.itemsize)
print(type(np_arr.dtype))
##size of 100 elements in  numpy array
print(np_arr.itemsize * np_arr.size)




4
<class 'numpy.dtypes.Int32DType'>
400


In [5]:
import sys
##size of one element in list

a=10
print(sys.getsizeof(a))

##size of 100 elements i  list
print(sys.getsizeof(1)* len(li_arr))






28
2800


In [10]:
import time
size = 100000

def addition_using_list():
    t1= time.time()
    a= range(size)
    b= range(size)
    c = [a[i] + b[i] for i in range(size)]
    t2 = time.time()
    return (t2-t1)

def addition_using_numpy():
    t1= time.time()
    a= np.arange(size)
    b= np.arange(size)
    c = a+b
    t2 = time.time()
    return (t2-t1)


t_list = addition_using_list()
t_numpy = addition_using_numpy()
print(('List =  ', t_list *1000))
print(('Numpy =  ', t_numpy *1000))











     





('List =  ', 65.79041481018066)
('Numpy =  ', 0.0)


In [11]:
a= [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))




[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
a= [1,2,3,4, '3']
b = np.array(a)
print(b)
print(type(b))


['1' '2' '3' '4' '3']
<class 'numpy.ndarray'>


In [13]:
b = np.array(a, dtype = int)
print(b)
print(type(b))

[1 2 3 4 3]
<class 'numpy.ndarray'>


In [14]:
b = np.array(a*3)
print(b)
print(type(b))

['1' '2' '3' '4' '3' '1' '2' '3' '4' '3' '1' '2' '3' '4' '3']
<class 'numpy.ndarray'>


In [16]:
b= np.ones(3)
b


array([1., 1., 1.])

In [17]:
b= np.ones(3,dtype=int)
b


array([1, 1, 1])

In [21]:
b= np.ones(3,4)
b


TypeError: Cannot interpret '4' as a data type

In [19]:
b= np.zeros(3)
b


array([0., 0., 0.])

In [20]:
b= np.zeros(3,4)
b


TypeError: Cannot interpret '4' as a data type

In [22]:
b= np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
b= np.ones((3,4))
b


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
b= np.full((3,4), 5)
b


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [26]:
b= np.arange(0,100)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
b= np.arange(0,100,3)
b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [30]:
b= np.linspace(0,100,30, dtype= int)
b

array([  0,   3,   6,  10,  13,  17,  20,  24,  27,  31,  34,  37,  41,
        44,  48,  51,  55,  58,  62,  65,  68,  72,  75,  79,  82,  86,
        89,  93,  96, 100])